import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/shared/sidebar/SideBar";
import MainHeader from "@/components/shared/header/MainHeader";
import PagePadding from "@/components/shared/main/PagePadding";
import GradientImage from "@/components/shared/main/GradientImage";
import PlayerWrapper from "@/components/shared/player/PlayerWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning>
        <div id="root" className="flex min-h-screen">
          <SideBar />
          <main className="flex-1 h-full main-content relative">
            <MainHeader />
            <GradientImage />
            <PlayerWrapper />
            <PagePadding>
              <div className="main-content-wrapper relative z-[60]">
                {children}
              </div>
            </PagePadding>
          </main>
        </div>
      </body>
    </html>
  );
}
